"""Models package initialization."""

from app.models.database import (
    Base,
    User,
    UserRole,
    Project,
    ProjectAssignment,
    TestCase,
    Execution,
    ExecutionStep,
    ExecutionStatus,
    Device,
    DeviceType,
    Platform,
    TestType,
    init_database,
    get_session,
)

from app.models.schemas import (
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    TestConfigurationRequest,
    DeviceValidationRequest,
    DeviceValidationResponse,
    ScriptGenerationRequest,
    ScriptGenerationResponse,
    TestCaseCreate,
    TestCaseResponse,
    ExecutionRequest,
    ExecutionResultSchema,
    ExecutionMetrics,
    ExecutionArtifacts,
    ExecutionStepSchema,
    ExecutionListItem,
    DeviceResponse,
    WebSocketMessage,
    StepUpdateMessage,
    ErrorResponse,
)

__all__ = [
    # Database models
    "Base",
    "User",
    "UserRole", 
    "Project",
    "ProjectAssignment",
    "TestCase",
    "Execution",
    "ExecutionStep",
    "ExecutionStatus",
    "Device",
    "DeviceType",
    "Platform",
    "TestType",
    "init_database",
    "get_session",
    # Schemas
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "TestConfigurationRequest",
    "DeviceValidationRequest",
    "DeviceValidationResponse",
    "ScriptGenerationRequest",
    "ScriptGenerationResponse",
    "TestCaseCreate",
    "TestCaseResponse",
    "ExecutionRequest",
    "ExecutionResultSchema",
    "ExecutionMetrics",
    "ExecutionArtifacts",
    "ExecutionStepSchema",
    "ExecutionListItem",
    "DeviceResponse",
    "WebSocketMessage",
    "StepUpdateMessage",
    "ErrorResponse",
]
